stages:
  - test
  - build
  - mirror

run_tests:
  stage: test
  image: docker.io/library/golang:1.25.0-alpine3.22

  before_script:
    - apk update && apk install make
  script:
    - make run-api-gateway
    - make run-user-services
  when: manual

mirror_to_github:
  stage: mirror
  image: alpine # A lightweight Linux image
  # rules:
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Only run on the default branch (e.g., main, master)
  before_script:
    - apk add --no-cache git git-lfs # Install git in the Alpine image
  script:
    - git config  --global user.email "xerofe@tuta.io"
    - git config  --global user.name "xerofenix"

    - git clone --bare https://gitlab.com/xerofenix/csd-cp.git /tmp/bare-repo
    - cd /tmp/bare-repo

    - git remote add github https://${GITHUB_MIRROR_TOKEN}@github.com/xerofenix/csd-cp.git

    - git push --mirror github
  when: on_success
